apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-java-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        {{- with .Values.podLabels }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "demo-java-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.githubID }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | nindent 12 }}
{{- else }}
            {}
{{- end }}
          volumeMounts:
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | nindent 12 }}
{{- else }}
            []
{{- end }}
      volumes:
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | nindent 8 }}
{{- else }}
        []
{{- end }}
      nodeSelector:
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | nindent 8 }}
{{- else }}
        {}
{{- end }}
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | nindent 8 }}
{{- else }}
        []
{{- end }}
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | nindent 8 }}
{{- else }}
        {}
{{- end }}
 
